-- SIMBARA v2 Supabase schema
-- Jalankan di Supabase SQL Editor sebelum menjalankan aplikasi.

create table if not exists public.items (
  id text primary key,
  name text not null,
  category text,
  brand text,
  serial_number text,
  location text not null,
  officer text,
  condition text not null default 'Baik',
  status text not null default 'Aktif',
  qr_link text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.locations (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.officers (
  id bigint generated by default as identity primary key,
  name text not null unique,
  position text,
  unit text,
  created_at timestamptz not null default now()
);

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  item_id text not null references public.items(id) on delete cascade,
  item_name text not null,
  location text not null,
  condition text,
  officer text,
  action text not null,
  notes text,
  type text not null check (type in ('verification', 'mutation', 'report')),
  created_at timestamptz not null default now()
);

create table if not exists public.system_profiles (
  id bigint primary key default 1,
  institution_name text not null default 'Lapas Kelas IIB Tanjung',
  address text,
  active_officer text not null default 'Admin',
  pin text not null default '1234',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint system_profiles_singleton check (id = 1)
);

alter table public.items enable row level security;
alter table public.locations enable row level security;
alter table public.officers enable row level security;
alter table public.activity_logs enable row level security;
alter table public.system_profiles enable row level security;

drop policy if exists "public read items" on public.items;
drop policy if exists "public write items" on public.items;
drop policy if exists "public read locations" on public.locations;
drop policy if exists "public write locations" on public.locations;
drop policy if exists "public read officers" on public.officers;
drop policy if exists "public write officers" on public.officers;
drop policy if exists "public read activity logs" on public.activity_logs;
drop policy if exists "public write activity logs" on public.activity_logs;
drop policy if exists "public read system profile" on public.system_profiles;
drop policy if exists "public write system profile" on public.system_profiles;

create policy "public read items" on public.items for select to anon using (true);
create policy "public write items" on public.items for all to anon using (true) with check (true);
create policy "public read locations" on public.locations for select to anon using (true);
create policy "public write locations" on public.locations for all to anon using (true) with check (true);
create policy "public read officers" on public.officers for select to anon using (true);
create policy "public write officers" on public.officers for all to anon using (true) with check (true);
create policy "public read activity logs" on public.activity_logs for select to anon using (true);
create policy "public write activity logs" on public.activity_logs for all to anon using (true) with check (true);
create policy "public read system profile" on public.system_profiles for select to anon using (true);
create policy "public write system profile" on public.system_profiles for all to anon using (true) with check (true);

insert into public.locations (code, name) values
  ('TU', 'Ruang Tata Usaha'),
  ('HUMAS', 'Ruang Humas'),
  ('KPLP', 'Ruang KPLP'),
  ('BINADIK', 'Ruang Binadik'),
  ('KAMTIB', 'Ruang Kamtib'),
  ('GUDANG', 'Gudang')
on conflict (code) do nothing;

insert into public.officers (name, position, unit) values
  ('Admin', 'Administrator', 'TU'),
  ('Andi', 'Staf TU', 'TU'),
  ('Budi', 'Staf Binadik', 'Binadik')
on conflict (name) do nothing;

insert into public.system_profiles (id, institution_name, address, active_officer, pin)
values (1, 'Lapas Kelas IIB Tanjung', '', 'Admin', '1234')
on conflict (id) do nothing;

create index if not exists idx_items_location on public.items(location);
create index if not exists idx_activity_logs_item_id on public.activity_logs(item_id);
create index if not exists idx_activity_logs_created_at on public.activity_logs(created_at desc);
